"""Constants shared by the history search GUI."""

DISPLAY_MODE_PLAIN = "全文拼接"
DISPLAY_MODE_LAYOUT = "按原位置排版"
DISPLAY_MODE_VALUES = (DISPLAY_MODE_PLAIN, DISPLAY_MODE_LAYOUT)

TEXT_SOURCE_BEFORE = "编辑前"
TEXT_SOURCE_AFTER = "编辑后"
TEXT_SOURCE_VALUES = (TEXT_SOURCE_BEFORE, TEXT_SOURCE_AFTER)

SORT_NEWEST_FIRST = "从晚到早"
SORT_OLDEST_FIRST = "从早到晚"
SORT_CUSTOM_RANGE = "自定义"
SORT_VALUES = (SORT_NEWEST_FIRST, SORT_OLDEST_FIRST, SORT_CUSTOM_RANGE)

MODE_FILTER_ALL = "全部"
MODE_FILTER_TEXT = "快速识别"
MODE_FILTER_DOCUMENT = "深度识别"
MODE_FILTER_VALUES = (MODE_FILTER_ALL, MODE_FILTER_TEXT, MODE_FILTER_DOCUMENT)

UPLOAD_FILTER_ALL = "全部"
UPLOAD_FILTER_IMAGE = "图片"
UPLOAD_FILTER_DOCUMENT = "文档"
UPLOAD_FILTER_VALUES = (UPLOAD_FILTER_ALL, UPLOAD_FILTER_IMAGE, UPLOAD_FILTER_DOCUMENT)

THUMBNAIL_SIZE = (132, 90)
GALLERY_CARD_WIDTH = 150
GALLERY_CARD_HEIGHT = 106
GALLERY_PADDING = 12
GALLERY_SCROLLBAR_GAP = 12
